apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: dotnet-api-app
description: Dotnet API App Deployment Pipeline
serialPipeline:
  stages:
  - targetId: staging
  - targetId: production
---
  
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: staging
description: Staging Environment
gke:
  cluster: projects/river-clover-404404/locations/us-central1/clusters/staging
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: production
description: Production Environment
gke:
  cluster: projects/river-clover-404404/locations/us-central1/clusters/production
